2018-10-17 17:17:48.584 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-17 17:17:48.587 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-17 17:17:48.588 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-17 17:17:48.590 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-17 17:17:48.590 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-17 17:18:48.801 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-17 17:18:48.804 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-17 17:18:48.804 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-17 17:18:48.806 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-17 17:18:48.806 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-17 17:20:36.409 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-17 17:20:36.411 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-17 17:20:36.411 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-17 17:20:36.413 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-17 17:20:36.413 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 13:19:11.118 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:19:11.121 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:19:11.122 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:19:11.125 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:19:11.125 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 13:22:40.159 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:22:40.161 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:22:40.162 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:22:40.163 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:22:40.164 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 13:24:08.018 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:24:08.020 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:24:08.021 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:24:08.023 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:24:08.023 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 13:26:14.485 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:26:14.487 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:26:14.488 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:26:14.489 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:26:14.490 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 13:28:34.502 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:28:34.504 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:28:34.505 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:28:34.507 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:28:34.509 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:28:34.510 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...} in application_master:init/4 line 134
2018-10-19 13:28:34.510 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...}
2018-10-19 13:28:34.510 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 13:28:34.510 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 13:28:34.510 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 13:33:07.624 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:33:07.627 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:33:07.627 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:33:07.629 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:33:07.632 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:33:07.632 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...} in application_master:init/4 line 134
2018-10-19 13:33:07.632 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...}
2018-10-19 13:33:07.632 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 13:33:07.632 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 13:33:07.633 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 13:33:40.496 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:33:40.498 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:33:40.499 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:33:40.501 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:33:40.503 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:33:40.503 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...} in application_master:init/4 line 134
2018-10-19 13:33:40.504 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...}
2018-10-19 13:33:40.504 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 13:33:40.504 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 13:33:40.504 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 13:35:25.607 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:35:25.610 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:35:25.610 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:35:25.612 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:35:25.614 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:35:25.615 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...} in application_master:init/4 line 134
2018-10-19 13:35:25.615 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...}
2018-10-19 13:35:25.615 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 13:35:25.615 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 13:35:25.615 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 13:36:25.340 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:36:25.342 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:36:25.343 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:36:25.345 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:36:25.347 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:36:25.347 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...} in application_master:init/4 line 134
2018-10-19 13:36:25.348 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{function_clause,[{gen,where,[{locale,chat_manager}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,...}]}]}}}},...}
2018-10-19 13:36:25.348 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 13:36:25.348 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 13:36:25.348 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 13:36:55.011 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:36:55.013 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:36:55.014 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:36:55.015 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:36:55.018 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{undef,[{chat_manager,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:36:55.018 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{undef,[{chat_manager,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{chat,start,[normal,[]]}} in application_master:init/4 line 134
2018-10-19 13:36:55.018 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{undef,[{chat_manager,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{chat,start,[normal,[]]}}
2018-10-19 13:36:55.018 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 13:36:55.018 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 13:36:55.019 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 13:37:56.475 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:37:56.478 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:37:56.479 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:37:56.482 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:37:56.485 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason {'EXIT',{undef,[{chat_manager,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 13:37:56.485 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{undef,[{chat_manager,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{chat,start,[normal,[]]}} in application_master:init/4 line 134
2018-10-19 13:37:56.485 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{'EXIT',{undef,[{chat_manager,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{chat,start,[normal,[]]}}
2018-10-19 13:37:56.486 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 13:37:56.486 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 13:37:56.486 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 13:38:20.650 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:38:20.653 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:38:20.653 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:38:20.655 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:38:34.872 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:38:34.875 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:38:34.876 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:38:34.878 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:39:15.910 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:39:15.912 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:39:15.913 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:39:15.915 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:39:16.025 [warning] <0.30.0> lager_error_logger_h dropped 61 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 13:39:16.025 [error] <0.107.0> gen_server <0.107.0> terminated with reason: no such process or port in call to gen_server:call(chat_room, {start_child,{"default",{"default",start_link,[]},permanent,5000,chat_room,["default"]}}, infinity) in gen_server:call/3 line 212
2018-10-19 13:39:16.027 [error] <0.107.0> CRASH REPORT Process <0.107.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chat_room, {start_child,{"default",{"default",start_link,[]},permanent,5000,chat_room,["default"]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 13:39:16.027 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no such process or port in call to gen_server:call(chat_room, {start_child,{"default",{"default",start_link,[]},permanent,5000,chat_room,["default"]}}, infinity) in context child_terminated
2018-10-19 13:39:16.027 [error] <0.211.0> CRASH REPORT Process <0.211.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:39:16.027 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:39:16.027 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:39:16.027 [error] <0.212.0> CRASH REPORT Process <0.212.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:39:16.027 [error] <0.213.0> CRASH REPORT Process <0.213.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:39:16.028 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:39:16.028 [error] <0.214.0> CRASH REPORT Process <0.214.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:39:16.028 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:39:16.028 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:39:16.028 [error] <0.215.0> CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:39:16.028 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason reached_max_restart_intensity in context shutdown
2018-10-19 13:39:16.028 [info] <0.31.0> Application chat exited with reason: shutdown
2018-10-19 13:39:30.446 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:39:30.448 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:39:30.449 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:39:30.451 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:39:36.679 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:39:36.681 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:39:36.682 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:39:36.684 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:40:22.443 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:40:22.445 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:40:22.446 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:40:22.448 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:42:13.319 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:42:13.321 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:42:13.321 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:42:13.323 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:42:33.359 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:42:33.361 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:42:33.362 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:42:33.364 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:43:45.558 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:43:45.561 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:43:45.561 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:43:45.564 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:48:55.667 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:48:55.669 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:48:55.670 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:48:55.673 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:49:17.917 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:49:17.919 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:49:17.920 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:49:17.922 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:49:18.032 [warning] <0.30.0> lager_error_logger_h dropped 61 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 13:49:18.032 [error] <0.107.0> gen_server <0.107.0> terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{default,start_link,[default]},permanent,5000,chat_room,[default]}}, infinity) in gen_server:call/3 line 212
2018-10-19 13:49:18.052 [error] <0.107.0> CRASH REPORT Process <0.107.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{default,start_link,[default]},permanent,5000,chat_room,[default]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 13:49:18.052 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{default,start_link,[default]},permanent,5000,chat_room,[default]}}, infinity) in context child_terminated
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:49:18.053 [error] <0.212.0> CRASH REPORT Process <0.212.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:49:18.053 [error] <0.213.0> CRASH REPORT Process <0.213.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:49:18.053 [error] <0.214.0> CRASH REPORT Process <0.214.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:49:18.053 [error] <0.215.0> CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:49:18.053 [error] <0.216.0> CRASH REPORT Process <0.216.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in gen_server:init_it/6 line 352
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason no match of right hand value {error,{already_started,<0.108.0>}} in chat_manager:init/1 line 32 in context start_error
2018-10-19 13:49:18.053 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at {restarting,<0.107.0>} exit with reason reached_max_restart_intensity in context shutdown
2018-10-19 13:49:18.053 [info] <0.31.0> Application chat exited with reason: shutdown
2018-10-19 13:50:29.129 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:50:29.131 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:50:29.132 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:50:29.134 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 13:59:39.693 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 13:59:39.695 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 13:59:39.696 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 13:59:39.697 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:01:14.976 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:01:14.979 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:01:14.979 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:01:14.981 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:02:17.050 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:02:17.052 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:02:17.053 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:02:17.055 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:02:54.321 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:02:54.324 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:02:54.324 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:02:54.326 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:02:54.328 [error] <0.107.0> CRASH REPORT Process <0.107.0> with 0 neighbours exited with reason: call to undefined function local:init([], {local,chat_manager}) in gen_server:init_it/6 line 352
2018-10-19 14:02:54.365 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at undefined exit with reason call to undefined function local:init([], {local,chat_manager}) in context start_error
2018-10-19 14:02:54.365 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{undef,[{local,init,[[],{local,chat_manager}],[]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{chat,start,[normal,[]]}} in application_master:init/4 line 134
2018-10-19 14:02:54.365 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chat_manager,{undef,[{local,init,[[],{local,chat_manager}],[]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{chat,start,[normal,[]]}}
2018-10-19 14:02:54.366 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 14:02:54.366 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 14:02:54.366 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 14:03:14.839 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:03:14.842 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:03:14.842 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:03:14.844 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:03:35.216 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:03:35.218 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:03:35.219 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:03:35.221 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:04:22.517 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:04:22.519 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:04:22.520 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:04:22.522 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:04:47.731 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:04:47.733 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:04:47.734 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:04:47.736 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:06:11.349 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:06:11.351 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:06:11.352 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:06:11.354 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:06:40.985 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:06:40.987 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:06:40.988 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:06:40.989 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:06:41.000 [warning] <0.30.0> lager_error_logger_h dropped 63 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 14:06:41.000 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 14:06:50.766 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:06:50.768 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:06:50.769 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:06:50.770 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:09:02.414 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:09:02.417 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:09:02.417 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:09:02.419 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:09:49.870 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:09:49.872 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:09:49.873 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:09:49.875 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:20:49.265 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:20:49.268 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:20:49.268 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:20:49.270 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:20:49.273 [error] <0.108.0> CRASH REPORT Process <0.108.0> with 0 neighbours exited with reason: call to undefined function local:init([], {local,chatroom_sup}) in gen_server:init_it/6 line 352
2018-10-19 14:20:49.292 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason call to undefined function local:init([], {local,chatroom_sup}) in context start_error
2018-10-19 14:20:49.292 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{undef,[{local,init,[[],{local,chatroom_sup}],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{chat,start,[normal,[]]}} in application_master:init/4 line 134
2018-10-19 14:20:49.292 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{undef,[{local,init,[[],{local,chatroom_sup}],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{chat,start,[normal,[]]}}
2018-10-19 14:20:49.293 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 14:20:49.293 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 14:20:49.293 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 14:21:41.175 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:21:41.178 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:21:41.178 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:21:41.180 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:21:41.183 [error] <0.108.0> CRASH REPORT Process <0.108.0> with 0 neighbours exited with reason: call to undefined function local:init([], {local,chatroom_sup}) in gen_server:init_it/6 line 352
2018-10-19 14:21:41.187 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason call to undefined function local:init([], {local,chatroom_sup}) in context start_error
2018-10-19 14:21:41.187 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{undef,[{local,init,[[],{local,chatroom_sup}],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{chat,start,[normal,[]]}} in application_master:init/4 line 134
2018-10-19 14:21:41.187 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{undef,[{local,init,[[],{local,chatroom_sup}],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{chat,start,[normal,[]]}}
2018-10-19 14:21:41.188 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 14:21:41.188 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 14:21:41.188 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 14:22:19.766 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:22:19.768 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:22:19.769 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:22:19.771 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:22:19.772 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 14:22:37.752 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:22:37.755 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:22:37.756 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:22:37.758 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:22:37.760 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 14:22:38.760 [warning] <0.30.0> lager_error_logger_h dropped 66 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 14:22:38.760 [error] <0.107.0> gen_server chat_manager terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:call/3 line 212
2018-10-19 14:22:38.779 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 14:22:38.779 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in context child_terminated
2018-10-19 14:22:39.780 [error] <0.212.0> gen_server chat_manager terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:call/3 line 212
2018-10-19 14:22:39.780 [error] <0.212.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 14:22:39.780 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.212.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in context child_terminated
2018-10-19 14:22:40.781 [error] <0.213.0> gen_server chat_manager terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:call/3 line 212
2018-10-19 14:22:40.781 [error] <0.213.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 14:22:40.782 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.213.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{chat_room,{chat_room,start_link,[default]},permanent,5000,worker,[chat_room]}}, infinity) in context child_terminated
2018-10-19 14:24:48.833 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:24:48.835 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:24:48.835 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:24:48.837 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:24:48.838 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 14:24:49.839 [warning] <0.30.0> lager_error_logger_h dropped 64 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 14:24:49.839 [error] <0.107.0> gen_server chat_manager terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in gen_server:call/3 line 212
2018-10-19 14:24:49.854 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 14:24:49.854 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in context child_terminated
2018-10-19 14:24:50.855 [error] <0.212.0> gen_server chat_manager terminated with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in gen_server:call/3 line 212
2018-10-19 14:24:50.855 [error] <0.212.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in gen_server:terminate/7 line 812
2018-10-19 14:24:50.855 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.212.0> exit with reason no such process or port in call to gen_server:call(chatroom_sup, {start_child,{default,{chat_room,start_link,[default]},temporary,5000,worker,[chat_room]}}, infinity) in context child_terminated
2018-10-19 14:26:09.155 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:26:09.158 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:26:09.158 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:26:09.160 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:26:09.161 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 14:26:10.163 [warning] <0.30.0> lager_error_logger_h dropped 66 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 14:26:10.164 [error] <0.107.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 14:26:10.184 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 14:26:10.184 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 14:26:11.185 [error] <0.212.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 14:26:11.185 [error] <0.212.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 14:26:11.186 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.212.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 14:27:54.148 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 14:27:54.151 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 14:27:54.151 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 14:27:54.153 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 14:27:54.154 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 14:27:55.157 [warning] <0.30.0> lager_error_logger_h dropped 64 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 14:27:55.158 [error] <0.107.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 14:27:55.174 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 14:27:55.175 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:20.570 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 15:11:20.572 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 15:11:20.573 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 15:11:20.575 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 15:11:20.576 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 15:11:21.578 [warning] <0.30.0> lager_error_logger_h dropped 66 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 15:11:21.579 [error] <0.107.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:21.594 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:21.595 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:22.597 [error] <0.212.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:22.597 [error] <0.212.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:22.597 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.212.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:23.598 [error] <0.213.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:23.599 [error] <0.213.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:23.599 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.213.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:24.599 [error] <0.214.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:24.600 [error] <0.214.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:24.600 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.214.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:25.601 [error] <0.215.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:25.601 [error] <0.215.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:25.602 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.215.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:26.603 [error] <0.216.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52
2018-10-19 15:11:26.604 [error] <0.216.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in gen_server:terminate/7 line 812
2018-10-19 15:11:26.604 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.216.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_info/2 line 52 in context child_terminated
2018-10-19 15:11:26.604 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.216.0> exit with reason reached_max_restart_intensity in context shutdown
2018-10-19 15:11:26.604 [info] <0.31.0> Application chat exited with reason: shutdown
2018-10-19 15:11:50.182 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 15:11:50.184 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 15:11:50.185 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 15:11:50.187 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 15:11:50.188 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 15:24:57.172 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 15:24:57.175 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 15:24:57.175 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 15:24:57.177 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 15:24:57.178 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 15:26:23.811 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 15:26:23.813 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 15:26:23.814 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 15:26:23.816 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 15:26:23.817 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 15:26:50.100 [warning] <0.30.0> lager_error_logger_h dropped 65 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 15:26:50.100 [error] <0.107.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40
2018-10-19 15:26:50.116 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in gen_server:terminate/7 line 812
2018-10-19 15:26:50.117 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in context child_terminated
2018-10-19 15:28:29.219 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 15:28:29.221 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 15:28:29.222 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 15:28:29.225 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 15:28:29.226 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 15:28:40.121 [warning] <0.30.0> lager_error_logger_h dropped 66 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 15:28:40.121 [error] <0.107.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40
2018-10-19 15:28:40.137 [error] <0.107.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in gen_server:terminate/7 line 812
2018-10-19 15:28:40.138 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.107.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in context child_terminated
2018-10-19 15:33:34.228 [error] <0.212.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40
2018-10-19 15:33:34.231 [error] <0.212.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in gen_server:terminate/7 line 812
2018-10-19 15:33:34.234 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.212.0> exit with reason no match of right hand value {error,{{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,handle_start_child,2,[{file,"supervisor.erl"},{line,724}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,422}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,...}]}},...}} in chat_manager:handle_call/3 line 40 in context child_terminated
2018-10-19 16:14:54.880 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:14:54.882 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:14:54.883 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:14:54.885 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:14:54.886 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 16:19:03.564 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:19:03.566 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:19:03.567 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:19:03.569 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:19:03.570 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 16:29:56.791 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:29:56.794 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:29:56.794 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:29:56.797 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:29:56.800 [error] <0.108.0> Supervisor {global,chatroom_sup} had child default started with chat_room:start_link(default) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:29:56.801 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,default,{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:29:56.801 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,default,{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:29:56.801 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,default,{'EXIT',{function_clause,[{gen,where,[{locale,default}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...}
2018-10-19 16:29:56.801 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 16:29:56.801 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 16:29:56.801 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 16:30:28.878 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:30:28.880 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:30:28.881 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:30:28.883 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:30:28.887 [error] <0.108.0> Supervisor {global,chatroom_sup} had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:30:28.887 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:30:28.887 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:30:28.887 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...}
2018-10-19 16:30:28.887 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 16:30:28.887 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 16:30:28.888 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 16:32:19.057 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:32:19.059 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:32:19.060 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:32:19.062 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:32:19.066 [error] <0.108.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:32:19.066 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:32:19.066 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:32:19.066 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...}
2018-10-19 16:32:19.066 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 16:32:19.066 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 16:32:19.067 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 16:33:26.445 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:33:26.448 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:33:26.448 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:33:26.450 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:33:26.453 [error] <0.107.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:33:26.453 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:33:26.454 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:33:26.454 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...}
2018-10-19 16:33:26.454 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 16:33:26.454 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 16:33:26.454 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 16:34:12.413 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:34:12.415 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:34:12.416 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:34:12.418 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:34:12.420 [error] <0.107.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:34:12.421 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:34:12.421 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:34:12.421 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...}
2018-10-19 16:34:12.421 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 16:34:12.421 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 16:34:12.422 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 16:35:36.625 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:35:36.627 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:35:36.628 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:35:36.630 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:35:36.631 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 16:38:12.158 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:38:12.160 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:38:12.161 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:38:12.164 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:38:12.167 [error] <0.107.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:38:12.167 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:38:12.167 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:38:12.167 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...}
2018-10-19 16:38:12.167 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 16:38:12.167 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 16:38:12.168 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 16:42:04.699 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:42:04.701 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:42:04.702 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:42:04.703 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:42:04.706 [error] <0.107.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:42:04.707 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:42:04.707 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:42:04.707 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...}
2018-10-19 16:42:04.707 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 16:42:04.707 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 16:42:04.707 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 16:42:51.044 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:42:51.046 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:42:51.047 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:42:51.049 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:42:51.051 [error] <0.107.0> Supervisor chatroom_sup had child chat_room started with chat_room:start_link(chat_room) at undefined exit with reason {'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-10-19 16:42:51.052 [error] <0.106.0> Supervisor chat_sup had child chatroom_sup started with chatroom_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}} in context start_error
2018-10-19 16:42:51.052 [error] <0.104.0> CRASH REPORT Process <0.104.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...} in application_master:init/4 line 134
2018-10-19 16:42:51.052 [info] <0.31.0> Application chat exited with reason: {{shutdown,{failed_to_start_child,chatroom_sup,{shutdown,{failed_to_start_child,chat_room,{'EXIT',{function_clause,[{gen,where,[{locale,chat_room}],[{file,"gen.erl"},{line,297}]},{gen,start,6,[{file,"gen.erl"},{line,75}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,...}]}}}}}},...}
2018-10-19 16:42:51.052 [info] <0.31.0> Application cowboy exited with reason: stopped
2018-10-19 16:42:51.052 [info] <0.31.0> Application cowlib exited with reason: stopped
2018-10-19 16:42:51.052 [info] <0.31.0> Application ranch exited with reason: stopped
2018-10-19 16:42:57.091 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 16:42:57.093 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 16:42:57.094 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 16:42:57.096 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 16:42:57.097 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 17:15:09.532 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 17:15:09.534 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 17:15:09.535 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 17:15:09.537 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 17:15:09.540 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 17:20:56.903 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 17:20:56.905 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 17:20:56.906 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 17:20:56.908 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 17:20:56.912 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 17:24:33.003 [warning] <0.30.0> lager_error_logger_h dropped 67 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 17:24:33.004 [error] <0.109.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 40
2018-10-19 17:24:33.004 [error] <0.109.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 40 in gen_server:terminate/7 line 812
2018-10-19 17:24:33.005 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.109.0> exit with reason no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 40 in context child_terminated
2018-10-19 17:25:02.595 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 17:25:02.597 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 17:25:02.598 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 17:25:02.600 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 17:25:02.604 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 17:25:34.521 [warning] <0.30.0> lager_error_logger_h dropped 65 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 17:25:34.521 [error] <0.109.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[newone]}}} in chat_manager:handle_call/3 line 40
2018-10-19 17:25:34.521 [error] <0.109.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[newone]}}} in chat_manager:handle_call/3 line 40 in gen_server:terminate/7 line 812
2018-10-19 17:25:34.523 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.109.0> exit with reason no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},permanent,5000,worker,[newone]}}} in chat_manager:handle_call/3 line 40 in context child_terminated
2018-10-19 17:29:44.333 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 17:29:44.335 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 17:29:44.336 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 17:29:44.338 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 17:29:44.342 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 17:29:52.040 [warning] <0.30.0> lager_error_logger_h dropped 67 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 17:29:52.040 [error] <0.109.0> gen_server chat_manager terminated with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},temporary,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 41
2018-10-19 17:29:52.066 [error] <0.109.0> CRASH REPORT Process chat_manager with 0 neighbours exited with reason: no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},temporary,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 41 in gen_server:terminate/7 line 812
2018-10-19 17:29:52.066 [error] <0.106.0> Supervisor chat_sup had child chat_manager started with chat_manager:start_link() at <0.109.0> exit with reason no match of right hand value {error,{{already_started,<0.108.0>},{child,undefined,newone,{chat_room,start_link,[newone]},temporary,5000,worker,[chat_room]}}} in chat_manager:handle_call/3 line 41 in context child_terminated
2018-10-19 17:30:32.239 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 17:30:32.241 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 17:30:32.242 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 17:30:32.244 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 17:30:32.247 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 17:30:34.247 [warning] <0.30.0> lager_error_logger_h dropped 67 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 18:20:19.277 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 18:20:19.279 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 18:20:19.280 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 18:20:19.281 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 18:20:19.287 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 18:21:43.444 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 18:21:43.446 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 18:21:43.447 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 18:21:43.449 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 18:21:43.452 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 18:22:18.422 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 18:22:18.424 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 18:22:18.424 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 18:22:18.426 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 18:22:18.429 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 18:22:25.426 [warning] <0.30.0> lager_error_logger_h dropped 66 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 18:22:25.426 [error] emulator Error in process <0.214.0> with exit value:
{[{reason,undef},{mfa,{chat_handler,websocket_init,3}},{stacktrace,[{cowboy_req,parse_qs,[{http_req,#Port<0.3359>,ranch_tcp,keepalive,<0.214.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},51814},<<"localhost">>,undefined,8080,<<"/ws">>,undefined,<<"room=myroom">>,undefined,[],[{<<"host">>,<<"localhost:8080">>},{<<"user-agent">>,<<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:62.0) Gecko/20100101 Firefox/62.0">>},{<<"accept">>,<<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>},{<<"accept-language">>,<<"ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"sec-websocket-version">>,<<"13">>},{<<"origin">>,<<"http://localhost:8080">>},{<<"sec-websocket-extensions">>,<<"permessage-deflate">>},{<<"sec-websocket-key">>,<<"OIC+9aek6/WOnDIJWZK0dw==">>},{<<"dnt">>,<<"1">>},{<<"connection">>,<<"keep-alive, Upgrade">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"upgrade">>,<<"websocket">>}],[{<<"sec-websocket-extensions">>,[{<<"permessage-deflate">>,[]}]},{<<"upgrade">>,[<<"websocket">>]},{<<"connection">>,[<<"keep-alive">>,<<"upgrade">>]}],undefined,[{websocket_compress,false},{websocket_version,13}],waiting,undefined,<<>>,false,waiting,[],<<>>,undefined}],[]},{chat_handler,websocket_init,3,[{file,"src/chat_handler.erl"},{line,20}]},{cowboy_websocket,handler_init,3,[{file,"src/cowboy_websocket.erl"},{line,140}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]},{req,[{socket,#Port<0.3359>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.214.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},51814}},{host,<<"localhost">>},{host_info,undefined},{port,8080},{path,<<"/ws">>},{path_info,undefined},{qs,<<"room=myroom">>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"localhost:8080">>},{<<"user-agent">>,<<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:62.0) Gecko/20100101 Firefox/62.0">>},{<<"accept">>,<<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>},{<<"accept-language">>,<<"ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"sec-websocket-version">>,<<"13">>},{<<"origin">>,<<"http://localhost:8080">>},{<<"sec-websocket-extensions">>,<<"permessage-deflate">>},{<<"sec-websocket-key">>,<<"OIC+9aek6/WOnDIJWZK0dw==">>},{<<"dnt">>,<<"1">>},{<<"connection">>,<<"keep-alive, Upgrade">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"upgrade">>,<<"websocket">>}]},{p_headers,[{<<"sec-websocket-extensions">>,[{<<"permessage-deflate">>,[]}]},{<<"upgrade">>,[<<"websocket">>]},{<<"connection">>,[<<"keep-alive">>,<<"upgrade">>]}]},{cookies,undefined},{meta,[{websocket_compress,false},{websocket_version,13}]},{body_state,waiting},{multipart,undefined},{buffer,<<>>},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{opts,[]}],[{cowboy_websocket,handler_init,3,[{file,"src/cowboy_websocket.erl"},{line,157}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}
2018-10-19 18:22:25.427 [error] <0.214.0> Ranch listener http terminated in chat_handler:websocket_init/3 with reason: call to undefined function cowboy_req:parse_qs({http_req,#Port<0.3359>,ranch_tcp,keepalive,<0.214.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},51814},<<"...">>,...})
2018-10-19 18:24:12.684 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 18:24:12.686 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 18:24:12.686 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 18:24:12.688 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 18:24:12.692 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 18:33:42.341 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 18:33:42.343 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 18:33:42.344 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 18:33:42.346 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 18:33:42.349 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 18:36:43.036 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 18:36:43.038 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 18:36:43.038 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 18:36:43.040 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 18:36:43.043 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 23:25:21.348 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 23:25:21.350 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 23:25:21.351 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 23:25:21.353 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 23:25:21.356 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 23:36:11.572 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 23:36:11.574 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 23:36:11.574 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 23:36:11.576 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 23:36:11.580 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 23:36:36.205 [warning] <0.30.0> lager_error_logger_h dropped 65 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 23:36:36.205 [error] emulator Error in process <0.214.0> with exit value:
{{try_clause,{ok,{state,<<"room1">>,<<"user)">>}}},[{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}
2018-10-19 23:36:36.205 [error] <0.214.0> Ranch listener http terminated with reason: no try clause matching {ok,{state,<<"room1">>,<<"user)">>}} in cowboy_websocket:handler_call/7 line 598
2018-10-19 23:38:12.655 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 23:38:12.657 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 23:38:12.658 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 23:38:12.660 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 23:38:12.663 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 23:38:18.967 [warning] <0.30.0> lager_error_logger_h dropped 67 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 23:38:18.967 [error] emulator Error in process <0.213.0> with exit value:
{{try_clause,{ok,{state,<<"room1">>,<<"user73284">>}}},[{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}
2018-10-19 23:38:18.967 [error] <0.213.0> Ranch listener http terminated with reason: no try clause matching {ok,{state,<<"room1">>,<<"user73284">>}} in cowboy_websocket:handler_call/7 line 598
2018-10-19 23:39:44.846 [error] emulator Error in process <0.216.0> with exit value:
{{try_clause,{ok,{state,<<"room1">>,<<"alex">>}}},[{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}
2018-10-19 23:39:44.846 [error] <0.216.0> Ranch listener http terminated with reason: no try clause matching {ok,{state,<<"room1">>,<<"alex">>}} in cowboy_websocket:handler_call/7 line 598
2018-10-19 23:40:14.679 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 23:40:14.681 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 23:40:14.682 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 23:40:14.684 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 23:40:14.687 [info] <0.31.0> Application chat started on node nonode@nohost
2018-10-19 23:40:19.538 [warning] <0.30.0> lager_error_logger_h dropped 67 messages in the last second that exceeded the limit of 50 messages/sec
2018-10-19 23:40:19.538 [error] emulator Error in process <0.213.0> with exit value:
{{try_clause,{ok,undefined_state}},[{cowboy_websocket,handler_call,7,[{file,"src/cowboy_websocket.erl"},{line,598}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,529}]}]}
2018-10-19 23:40:19.538 [error] <0.213.0> Ranch listener http terminated with reason: no try clause matching {ok,undefined_state} in cowboy_websocket:handler_call/7 line 598
2018-10-19 23:42:18.846 [info] <0.31.0> Application lager started on node nonode@nohost
2018-10-19 23:42:18.848 [info] <0.31.0> Application ranch started on node nonode@nohost
2018-10-19 23:42:18.849 [info] <0.31.0> Application cowlib started on node nonode@nohost
2018-10-19 23:42:18.850 [info] <0.31.0> Application cowboy started on node nonode@nohost
2018-10-19 23:42:18.854 [info] <0.31.0> Application chat started on node nonode@nohost
